name: Run All Tests
on:
  pull_request:
    branches: [develop]
    types: [opened, reopened, synchronize]
  workflow_dispatch:
jobs:
  info:
    name: Gather info for jobs
    # Gathering info should never take longer than 1 minute
    timeout-minutes: 1
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.target_branch.outputs.branch }}
      changed_theme: ${{ steps.changed_theme.outputs.any_changed }}
      env_name: ${{ steps.environment.outputs.name }}
    steps:
      - name: Get target branch
        run: |
          branch=${{ github.event.pull_request.base.ref }}
          echo "branch=${branch}" >> $GITHUB_OUTPUT

          echo "::group::Branch"
          echo 'branch: '${branch}
          echo "::endgroup::"
        shell: bash
        id: target_branch

      - name: Get environment
        run: |
          env=dev
          if [[ "${{ steps.target_branch.outputs.name }}" == "main" ]]; then
            env=prod
          fi
          echo "name=${env}" >> $GITHUB_OUTPUT

          echo "::group::Environment"
          echo 'environment: '${env}
          echo "::endgroup::"
        shell: bash
        id: environment

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed theme files
        id: changed_theme
        uses: tj-actions/changed-files@v39
        with:
          files: |
            themes/**

      - name: Did Theme Change
        run: |
          echo "::group::Changes"
          echo 'Changed?: '${{ steps.changed_theme.outputs.any_changed }}
          echo "::endgroup::"
        shell: bash

  test:
    name: Lint and test
    # Linting and Testing should never take longer than 15 minutes
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: [info]
    if: ${{ needs.info.outputs.changed_theme == 'true' }}
    environment:
      name: ${{ needs.info.outputs.env_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint
        uses: 10up/wpcs-action@stable
        with:
          paths: './themes' # Paths to check, space separated
          standard: 'WordPress' # Standard to use. Accepts WordPress|WordPress-Core|WordPress-Docs|WordPress-Extra|WordPress-VIP-Go|WordPressVIPMinimum|10up-Default.
          extra_args: '--report-json=./phpcs.json'

      - name: Update summary
        run: |
          npm i -g github:10up/phpcs-json-to-md
          phpcs-json-to-md --path ./phpcs.json --output ./phpcs.md
          cat phpcs.md >> $GITHUB_STEP_SUMMARY
        shell: bash
        if: always()
